#!/usr/bin/env php
<?php
require(dirname(__DIR__).'/vendor/autoload.php');

if(!isset($argv[1])) {
  echo "Pass an ID\n";
  exit(1);
}

$obj = new Choval\LID($argv[1]);
$number = $obj->number();
$id = $obj->id();
$web = $obj->web();
echo "
NUM: $number
WEB: $web
LID: $id

";


