#!/usr/bin/env php
<?php
require(__DIR__.'/../src/Hid.php');

if(!isset($argv[1])) {
  echo "Pass an ID\n";
  exit(1);
}

$obj = new Choval\HID($argv[1]);
$number = $obj->number();
$hid = $obj->hid();
$url = $obj->url();
echo "
 NUMBER: $number
    HID: $hid
URL HID: $url

";


